services:
  mongo:
    image: mongo:8.2.2
    container_name: mongodb-prod
    ports:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  backend:
    image: ghcr.io/chariot-group/codex-api-production:latest
    container_name: backend-prod
    restart: unless-stopped
    working_dir: /app
    environment:
      - API_PORT=${API_PORT}  # Port interne fixe
      - MONGO_URL=${MONGO_URL}
      - NODE_ENV=${NODE_ENV}
      - API_VERSION=${API_VERSION}
      - API_URL=${API_URL}
      - SSO_URL=${SSO_URL}
      - SSO_REALM=${SSO_REALM}
      - SSO_CLIENT_ID=${SSO_CLIENT_ID}
    depends_on:
      mongo:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.codex-api.rule=Host(`${API_DOMAIN}`)"
      - "traefik.http.routers.codex-api.entrypoints=websecure"
      - "traefik.http.routers.codex-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.codex-api.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public
      - internal

volumes:
  mongodb_data:

networks:
  internal:
    driver: bridge
  traefik-public:
    external: true
