services:
  mongo:
    image: mongo:8.2.2
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    command:
      - "--logpath"
      - "/var/log/mongodb/mongod.log"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: backend
    working_dir: /app
    ports:
      - "${API_PORT}:9000"
    environment:
      - API_PORT=${API_PORT}
      - MONGO_URL=${MONGO_URL}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongodb_data:
