# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci --include=dev

COPY . .

# Build the application
RUN npm run build && \
    echo "=== Checking build output ===" && \
    ls -laR dist/ && \
    echo "=== End build output ===" && \
    mkdir -p dist/src/script/output && \
    cp src/script/output/*.json dist/src/script/output/

# Production stage
FROM node:20-alpine AS production

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Copy built application from builder stage
COPY --from=builder /app/dist ./dist

CMD [ "node", "dist/src/main.js" ]

EXPOSE ${API_PORT}