FROM node:25-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci --include=dev

COPY . .

# Build the application
RUN npm run build

# Remove dev dependencies after build
RUN npm prune --production

CMD [ "node", "dist/main.js" ]

EXPOSE ${API_PORT}